### Create Account
# @prompt description description of account
POST http://127.0.0.1:3000/accounts HTTP/1.1
content-type: application/json
Authorization: token xxx

{
    "entity_id": "{{$guid}}",
    "description": "{{description}}"
}

### Get Accounts
GET http://127.0.0.1:3000/accounts HTTP/1.1
content-type: application/json
Authorization: token xxx


### Update Account
